name: Check PR title

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  conventional-title:
    runs-on: ubuntu-latest
    if:
      ${{ github.actor != 'dependabot[bot]' && github.actor !=
      'dependabot-preview[bot]' }}
    permissions:
      statuses: write
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
