# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  build:
    if: github.event.pull_request.user.login != 'Dependabot[bot]'
    strategy:
      matrix:
        node-version:
          - 18.16.0
          - 20.7.0
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
