# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ main ]

env:
  CI: true

jobs:
  build:
    strategy:
      matrix:
        node-version: [ 10.24 ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.24
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      # - run: npm run test
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
