# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tag on Merge

on:
  push:
    branches: [main]

env:
  CI: true

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.16.0]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 18.16.0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
      - run:
          npm version --allow-same-version=true --git-tag-version=false $(git
          describe --tags)
      - name: Commit Package Version
        id: commit
        run: |-
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain package.json)" ]; then
            git add package.json
            git add package-lock.json
            git commit -m "[ci skip] chore(package.json): update package json"
            echo "exit_code=0" >> $GITHUB_OUTPUT
          else
            echo "exit_code=1" >> $GITHUB_OUTPUT
          fi
      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        if: steps.commit.outputs.exit_code == 0
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: main
          unprotect_reviews: true
